import 'dart:io';

import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:provider/provider.dart';
import '../provider/auth_provider.dart';

void showSnackBar(BuildContext context, String content) {
  ScaffoldMessenger.of(context).showSnackBar(
    SnackBar(
      content: Text(content),
    ),
  );
}

Future<File?> pickImage(BuildContext context) async {
  File? image;
  try {
    final pickedImage =
    await ImagePicker().pickImage(source: ImageSource.gallery);
    if (pickedImage != null) {
      image = File(pickedImage.path);
    }
  } catch (e) {
    showSnackBar(context, e.toString());
  }

  return image;
}

Future<File?> pickDocument(BuildContext context) async {
  File? image;
  try {
    final pickedImage =
    await FilePicker.platform.pickFiles( dialogTitle:  'Report', type: FileType.custom, allowedExtensions: ['pdf', 'doc', 'docx', 'txt', 'jpg', 'jpeg', 'png']);
    if (pickedImage != null) {
      image = File(pickedImage.files.single.path!);
    }
  } catch (e) {
    showSnackBar(context, e.toString());
  }

  return image;
}


enum NotificationType {
  accountCreation,
  bookingScheduled,
  bookingComplete,
  reportUploaded,
  prescriptionUploaded,
  dietGenerated,
  defaultMessage,
  bookingPending,
}

String createMessage(NotificationType type, String patientName, String clinicName, {String? date, String? doctorName}) {
  switch (type) {
    case NotificationType.accountCreation:
      return 'Dear $patientName,\n\nYour account has been successfully created by $clinicName.\n\nBest Regards,\n$clinicName';
    case NotificationType.bookingScheduled:
      return 'Dear $patientName,\n\nYour booking has been scheduled for $date with Dr. $doctorName by $clinicName.\n\nBest Regards,\n$clinicName';
    case NotificationType.bookingComplete:
      return 'Dear $patientName,\n\nYour booking is complete. Thank you for choosing $clinicName.\n\nBest Regards,\n$clinicName';
    case NotificationType.reportUploaded:
      return 'Dear $patientName,\n\nYour report has been uploaded by $clinicName.\n\nBest Regards,\n$clinicName';
    case NotificationType.prescriptionUploaded:
      return 'Dear $patientName,\n\nYour prescription has been uploaded by $clinicName.\n\nBest Regards,\n$clinicName';
    case NotificationType.dietGenerated:
      return 'Dear $patientName,\n\nYour diet plan has been generated by $clinicName.\n\nBest Regards,\n$clinicName';
    case NotificationType.bookingPending:
      return 'Dear $patientName,\n\nYour booking is pending with $clinicName. We will notify you once it is confirmed.\n\nBest Regards,\n$clinicName';
    default:
      return 'Dear $patientName,\n\nYou have a new message from $clinicName.\n\nBest Regards,\n$clinicName';
  }
}




